stages:
  - test

tests:
  stage: test
  tags:
    - kubernetes
  image: python:3.5
  script:
    - mkdir -p .pip-cache
    - pip --cache-dir .pip-cache install -qr requirements.txt
    - pip --cache-dir .pip-cache install -qr dev-requirements.txt
    - flake8
    - tests/certificates/generate_certificates.sh
    - cp -r tests/certificates/certs/ tests/certificates/certs2
    - python -m unittest discover -s tests/
  cache:
    paths:
      - .pip-cache
